# Generated by Django 5.1.4 on 2026-07-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=20)),
                ('certificate', models.CharField(max_length=10)),
                ('release_date', models.DateField()),
                ('interested', models.IntegerField(default=0)),
                ('poster', models.URLField()),
                ('banner', models.URLField()),
                ('trailer', models.URLField(blank=True)),
            ],
        ),
    ]
