# Generated by Django 5.1.4 on 2026-07-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyshow_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='trailer',
        ),
    ]
