# Generated by Django 5.1.4 on 2026-08-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyshow_app', '0003_genre_remove_movie_genre_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=20)),
                ('certificate', models.CharField(max_length=10)),
                ('release_date', models.DateField()),
                ('interested', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=100)),
                ('rent', models.IntegerField(default=0)),
                ('poster', models.URLField()),
            ],
        ),
    ]
