# Generated by Django 5.1.4 on 2026-08-03 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyshow_app', '0005_streamtype_stream_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='type',
        ),
        migrations.AddField(
            model_name='stream',
            name='stream_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='bookmyshow_app.streamtype'),
            preserve_default=False,
        ),
    ]
