# Generated by Django 5.1.4 on 2026-08-11 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyshow_app', '0006_remove_stream_type_stream_stream_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('interested', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('starttime', models.TimeField()),
                ('duration', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('about', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bookmyshow_app.eventtype')),
                ('lang', models.ManyToManyField(to='bookmyshow_app.language')),
            ],
        ),
    ]
